# Generated by Django 3.0.6 on 2020-05-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0004_auto_20200505_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
