# Generated by Django 3.0.6 on 2020-05-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0008_auto_20200508_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryarticles',
            options={'verbose_name': 'Категория статей', 'verbose_name_plural': 'Категории статей'},
        ),
    ]
