# Generated by Django 3.0.6 on 2020-05-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0009_auto_20200508_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='img_to_slider',
            field=models.BooleanField(default=False),
        ),
    ]
