# Generated by Django 3.0.6 on 2020-05-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0010_articles_img_to_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
    ]
