# Generated by Django 3.0.6 on 2020-05-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200508_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slider',
            field=models.BooleanField(default=False),
        ),
    ]
