# Generated by Django 3.0.6 on 2020-05-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='slider',
            new_name='img_to_slider',
        ),
    ]
