# Generated by Django 3.0.6 on 2020-05-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_newprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewProfile',
        ),
    ]
