# Generated by Django 3.0.6 on 2020-05-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_newprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/image_user/noimage.png', upload_to='media/image_user'),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
